// Code generated by mockery v1.0.0
package kv

import mock "github.com/stretchr/testify/mock"

// MockDatabase is an autogenerated mock type for the Database type
type MockDatabase struct {
	mock.Mock
}

// Begin provides a mock function with given fields: writable
func (_m *MockDatabase) Begin(writable bool) Transaction {
	ret := _m.Called(writable)

	var r0 Transaction
	if rf, ok := ret.Get(0).(func(bool) Transaction); ok {
		r0 = rf(writable)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Transaction)
		}
	}

	return r0
}

// Close provides a mock function with given fields:
func (_m *MockDatabase) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
