// Code generated by mockery v1.0.0
package kv

import buntdb "github.com/tidwall/buntdb"
import mock "github.com/stretchr/testify/mock"

// MockDatabase is an autogenerated mock type for the Database type
type MockDatabase struct {
	mock.Mock
}

// Begin provides a mock function with given fields: writeable
func (_m *MockDatabase) Begin(writeable bool) (*buntdb.Tx, error) {
	ret := _m.Called(writeable)

	var r0 *buntdb.Tx
	if rf, ok := ret.Get(0).(func(bool) *buntdb.Tx); ok {
		r0 = rf(writeable)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*buntdb.Tx)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(bool) error); ok {
		r1 = rf(writeable)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
