// Code generated by go generate; DO NOT EDIT.

package migration

var systemContractsDataSQL = `
INSERT INTO "system_contracts" (id, name, value, conditions)
VALUES
	(next_id('system_contracts'), 'FirstBlock', 'contract FirstBlock {
    data {
        Data string
    }

    conditions {
    }

    action {
        InitFirstEcosystem($Data)
    }
}
', 'ContractConditions("MainCondition")');
`