// Code generated by golex. DO NOT EDIT.

package parser

import (
	"strconv"

	"github.com/cznic/golex/lex"
)

func (l *lexer) scan(lval *yySymType) lex.Char {
	c := l.Enter()

yystate0:
	yyrule := -1
	_ = yyrule
	c = l.Rule0()

	goto yystart1

	goto yystate0 // silence unused label error
	goto yyAction // silence unused label error
yyAction:
	switch yyrule {
	case 1:
		goto yyrule1
	case 2:
		goto yyrule2
	case 3:
		goto yyrule3
	case 4:
		goto yyrule4
	case 5:
		goto yyrule5
	case 6:
		goto yyrule6
	case 7:
		goto yyrule7
	case 8:
		goto yyrule8
	case 9:
		goto yyrule9
	case 10:
		goto yyrule10
	case 11:
		goto yyrule11
	case 12:
		goto yyrule12
	case 13:
		goto yyrule13
	case 14:
		goto yyrule14
	case 15:
		goto yyrule15
	case 16:
		goto yyrule16
	case 17:
		goto yyrule17
	case 18:
		goto yyrule18
	case 19:
		goto yyrule19
	case 20:
		goto yyrule20
	case 21:
		goto yyrule21
	case 22:
		goto yyrule22
	case 23:
		goto yyrule23
	case 24:
		goto yyrule24
	case 25:
		goto yyrule25
	case 26:
		goto yyrule26
	case 27:
		goto yyrule27
	case 28:
		goto yyrule28
	case 29:
		goto yyrule29
	case 30:
		goto yyrule30
	case 31:
		goto yyrule31
	case 32:
		goto yyrule32
	case 33:
		goto yyrule33
	case 34:
		goto yyrule34
	case 35:
		goto yyrule35
	case 36:
		goto yyrule36
	case 37:
		goto yyrule37
	case 38:
		goto yyrule38
	case 39:
		goto yyrule39
	case 40:
		goto yyrule40
	case 41:
		goto yyrule41
	case 42:
		goto yyrule42
	case 43:
		goto yyrule43
	case 44:
		goto yyrule44
	case 45:
		goto yyrule45
	case 46:
		goto yyrule46
	case 47:
		goto yyrule47
	case 48:
		goto yyrule48
	case 49:
		goto yyrule49
	case 50:
		goto yyrule50
	case 51:
		goto yyrule51
	case 52:
		goto yyrule52
	case 53:
		goto yyrule53
	case 54:
		goto yyrule54
	case 55:
		goto yyrule55
	case 56:
		goto yyrule56
	case 57:
		goto yyrule57
	case 58:
		goto yyrule58
	case 59:
		goto yyrule59
	case 60:
		goto yyrule60
	case 61:
		goto yyrule61
	case 62:
		goto yyrule62
	case 63:
		goto yyrule63
	case 64:
		goto yyrule64
	case 65:
		goto yyrule65
	}
	goto yystate1 // silence unused label error
yystate1:
	c = l.Next()
yystart1:
	switch {
	default:
		goto yyabort
	case c == '!':
		goto yystate3
	case c == '"':
		goto yystate5
	case c == '$':
		goto yystate7
	case c == '%':
		goto yystate9
	case c == '&':
		goto yystate11
	case c == '(':
		goto yystate13
	case c == ')':
		goto yystate14
	case c == '*':
		goto yystate15
	case c == '+':
		goto yystate17
	case c == ',':
		goto yystate20
	case c == '-':
		goto yystate21
	case c == '.':
		goto yystate24
	case c == '/':
		goto yystate27
	case c == ':':
		goto yystate31
	case c == '<':
		goto yystate32
	case c == '=':
		goto yystate34
	case c == '>':
		goto yystate36
	case c == '[':
		goto yystate39
	case c == '\t' || c == '\n' || c == '\r' || c == ' ':
		goto yystate2
	case c == ']':
		goto yystate40
	case c == 'a':
		goto yystate41
	case c == 'b':
		goto yystate51
	case c == 'c':
		goto yystate63
	case c == 'd':
		goto yystate81
	case c == 'e':
		goto yystate85
	case c == 'f':
		goto yystate93
	case c == 'i':
		goto yystate108
	case c == 'm':
		goto yystate114
	case c == 'n':
		goto yystate121
	case c == 'r':
		goto yystate124
	case c == 's':
		goto yystate130
	case c == 't':
		goto yystate136
	case c == 'v':
		goto yystate140
	case c == 'w':
		goto yystate143
	case c == '{':
		goto yystate154
	case c == '|':
		goto yystate155
	case c == '}':
		goto yystate157
	case c >= '0' && c <= '9':
		goto yystate29
	case c >= 'A' && c <= 'Z' || c == '_' || c == 'g' || c == 'h' || c >= 'j' && c <= 'l' || c >= 'o' && c <= 'q' || c == 'u' || c >= 'x' && c <= 'z' || c == '\u0080':
		goto yystate38
	}

yystate2:
	c = l.Next()
	yyrule = 1
	l.Mark()
	switch {
	default:
		goto yyrule1
	case c == '\t' || c == '\n' || c == '\r' || c == ' ':
		goto yystate2
	}

yystate3:
	c = l.Next()
	yyrule = 19
	l.Mark()
	switch {
	default:
		goto yyrule19
	case c == '=':
		goto yystate4
	}

yystate4:
	c = l.Next()
	yyrule = 18
	l.Mark()
	goto yyrule18

yystate5:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == '"':
		goto yystate6
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate5
	}

yystate6:
	c = l.Next()
	yyrule = 65
	l.Mark()
	goto yyrule65

yystate7:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080':
		goto yystate8
	}

yystate8:
	c = l.Next()
	yyrule = 61
	l.Mark()
	switch {
	default:
		goto yyrule61
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate8
	}

yystate9:
	c = l.Next()
	yyrule = 16
	l.Mark()
	switch {
	default:
		goto yyrule16
	case c == '=':
		goto yystate10
	}

yystate10:
	c = l.Next()
	yyrule = 6
	l.Mark()
	goto yyrule6

yystate11:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == '&':
		goto yystate12
	}

yystate12:
	c = l.Next()
	yyrule = 10
	l.Mark()
	goto yyrule10

yystate13:
	c = l.Next()
	yyrule = 28
	l.Mark()
	goto yyrule28

yystate14:
	c = l.Next()
	yyrule = 29
	l.Mark()
	goto yyrule29

yystate15:
	c = l.Next()
	yyrule = 14
	l.Mark()
	switch {
	default:
		goto yyrule14
	case c == '=':
		goto yystate16
	}

yystate16:
	c = l.Next()
	yyrule = 4
	l.Mark()
	goto yyrule4

yystate17:
	c = l.Next()
	yyrule = 12
	l.Mark()
	switch {
	default:
		goto yyrule12
	case c == '+':
		goto yystate18
	case c == '=':
		goto yystate19
	}

yystate18:
	c = l.Next()
	yyrule = 8
	l.Mark()
	goto yyrule8

yystate19:
	c = l.Next()
	yyrule = 2
	l.Mark()
	goto yyrule2

yystate20:
	c = l.Next()
	yyrule = 26
	l.Mark()
	goto yyrule26

yystate21:
	c = l.Next()
	yyrule = 13
	l.Mark()
	switch {
	default:
		goto yyrule13
	case c == '-':
		goto yystate22
	case c == '=':
		goto yystate23
	}

yystate22:
	c = l.Next()
	yyrule = 9
	l.Mark()
	goto yyrule9

yystate23:
	c = l.Next()
	yyrule = 3
	l.Mark()
	goto yyrule3

yystate24:
	c = l.Next()
	yyrule = 25
	l.Mark()
	switch {
	default:
		goto yyrule25
	case c == '.':
		goto yystate25
	}

yystate25:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == '.':
		goto yystate26
	}

yystate26:
	c = l.Next()
	yyrule = 24
	l.Mark()
	goto yyrule24

yystate27:
	c = l.Next()
	yyrule = 15
	l.Mark()
	switch {
	default:
		goto yyrule15
	case c == '=':
		goto yystate28
	}

yystate28:
	c = l.Next()
	yyrule = 5
	l.Mark()
	goto yyrule5

yystate29:
	c = l.Next()
	yyrule = 62
	l.Mark()
	switch {
	default:
		goto yyrule62
	case c == '.':
		goto yystate30
	case c >= '0' && c <= '9':
		goto yystate29
	}

yystate30:
	c = l.Next()
	yyrule = 63
	l.Mark()
	switch {
	default:
		goto yyrule63
	case c >= '0' && c <= '9':
		goto yystate30
	}

yystate31:
	c = l.Next()
	yyrule = 27
	l.Mark()
	goto yyrule27

yystate32:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c == '=':
		goto yystate33
	}

yystate33:
	c = l.Next()
	yyrule = 20
	l.Mark()
	goto yyrule20

yystate34:
	c = l.Next()
	yyrule = 7
	l.Mark()
	switch {
	default:
		goto yyrule7
	case c == '=':
		goto yystate35
	}

yystate35:
	c = l.Next()
	yyrule = 17
	l.Mark()
	goto yyrule17

yystate36:
	c = l.Next()
	yyrule = 23
	l.Mark()
	switch {
	default:
		goto yyrule23
	case c == '=':
		goto yystate37
	}

yystate37:
	c = l.Next()
	yyrule = 21
	l.Mark()
	goto yyrule21

yystate38:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate39:
	c = l.Next()
	yyrule = 32
	l.Mark()
	goto yyrule32

yystate40:
	c = l.Next()
	yyrule = 33
	l.Mark()
	goto yyrule33

yystate41:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'c':
		goto yystate42
	case c == 'r':
		goto yystate47
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c == 'a' || c == 'b' || c >= 'd' && c <= 'q' || c >= 's' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate42:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 't':
		goto yystate43
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate43:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'i':
		goto yystate44
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate44:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'o':
		goto yystate45
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate45:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'n':
		goto yystate46
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate46:
	c = l.Next()
	yyrule = 37
	l.Mark()
	switch {
	default:
		goto yyrule37
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate47:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'r':
		goto yystate48
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate48:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'a':
		goto yystate49
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate49:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'y':
		goto yystate50
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'x' || c == 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate50:
	c = l.Next()
	yyrule = 58
	l.Mark()
	switch {
	default:
		goto yyrule58
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate51:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'o':
		goto yystate52
	case c == 'r':
		goto yystate55
	case c == 'y':
		goto yystate59
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c == 'p' || c == 'q' || c >= 's' && c <= 'x' || c == 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate52:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'o':
		goto yystate53
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate53:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'l':
		goto yystate54
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'k' || c >= 'm' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate54:
	c = l.Next()
	yyrule = 52
	l.Mark()
	switch {
	default:
		goto yyrule52
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate55:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'e':
		goto yystate56
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate56:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'a':
		goto yystate57
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate57:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'k':
		goto yystate58
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'j' || c >= 'l' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate58:
	c = l.Next()
	yyrule = 45
	l.Mark()
	switch {
	default:
		goto yyrule45
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate59:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 't':
		goto yystate60
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate60:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'e':
		goto yystate61
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate61:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 's':
		goto yystate62
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'r' || c >= 't' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate62:
	c = l.Next()
	yyrule = 57
	l.Mark()
	switch {
	default:
		goto yyrule57
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate63:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'o':
		goto yystate64
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate64:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'n':
		goto yystate65
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate65:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'd':
		goto yystate66
	case c == 't':
		goto yystate72
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'c' || c >= 'e' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate66:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'i':
		goto yystate67
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate67:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 't':
		goto yystate68
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate68:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'i':
		goto yystate69
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate69:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'o':
		goto yystate70
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate70:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'n':
		goto yystate71
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate71:
	c = l.Next()
	yyrule = 36
	l.Mark()
	switch {
	default:
		goto yyrule36
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate72:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'i':
		goto yystate73
	case c == 'r':
		goto yystate77
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'q' || c >= 's' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate73:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'n':
		goto yystate74
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate74:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'u':
		goto yystate75
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 't' || c >= 'v' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate75:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'e':
		goto yystate76
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate76:
	c = l.Next()
	yyrule = 46
	l.Mark()
	switch {
	default:
		goto yyrule46
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate77:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'a':
		goto yystate78
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate78:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'c':
		goto yystate79
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c == 'a' || c == 'b' || c >= 'd' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate79:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 't':
		goto yystate80
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate80:
	c = l.Next()
	yyrule = 34
	l.Mark()
	switch {
	default:
		goto yyrule34
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate81:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'a':
		goto yystate82
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate82:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 't':
		goto yystate83
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate83:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'a':
		goto yystate84
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate84:
	c = l.Next()
	yyrule = 35
	l.Mark()
	switch {
	default:
		goto yyrule35
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate85:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'l':
		goto yystate86
	case c == 'r':
		goto yystate89
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'k' || c >= 'm' && c <= 'q' || c >= 's' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate86:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 's':
		goto yystate87
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'r' || c >= 't' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate87:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'e':
		goto yystate88
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate88:
	c = l.Next()
	yyrule = 43
	l.Mark()
	switch {
	default:
		goto yyrule43
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate89:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'r':
		goto yystate90
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate90:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'o':
		goto yystate91
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate91:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'r':
		goto yystate92
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate92:
	c = l.Next()
	yyrule = 49
	l.Mark()
	switch {
	default:
		goto yyrule49
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate93:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'a':
		goto yystate94
	case c == 'i':
		goto yystate98
	case c == 'l':
		goto yystate101
	case c == 'u':
		goto yystate105
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'h' || c == 'j' || c == 'k' || c >= 'm' && c <= 't' || c >= 'v' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate94:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'l':
		goto yystate95
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'k' || c >= 'm' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate95:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 's':
		goto yystate96
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'r' || c >= 't' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate96:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'e':
		goto yystate97
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate97:
	c = l.Next()
	yyrule = 41
	l.Mark()
	switch {
	default:
		goto yyrule41
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate98:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'l':
		goto yystate99
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'k' || c >= 'm' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate99:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'e':
		goto yystate100
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate100:
	c = l.Next()
	yyrule = 60
	l.Mark()
	switch {
	default:
		goto yyrule60
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate101:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'o':
		goto yystate102
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate102:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'a':
		goto yystate103
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate103:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 't':
		goto yystate104
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate104:
	c = l.Next()
	yyrule = 54
	l.Mark()
	switch {
	default:
		goto yyrule54
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate105:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'n':
		goto yystate106
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate106:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'c':
		goto yystate107
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c == 'a' || c == 'b' || c >= 'd' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate107:
	c = l.Next()
	yyrule = 38
	l.Mark()
	switch {
	default:
		goto yyrule38
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate108:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'f':
		goto yystate109
	case c == 'n':
		goto yystate110
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'e' || c >= 'g' && c <= 'm' || c >= 'o' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate109:
	c = l.Next()
	yyrule = 42
	l.Mark()
	switch {
	default:
		goto yyrule42
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate110:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'f':
		goto yystate111
	case c == 't':
		goto yystate113
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'e' || c >= 'g' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate111:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'o':
		goto yystate112
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate112:
	c = l.Next()
	yyrule = 47
	l.Mark()
	switch {
	default:
		goto yyrule47
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate113:
	c = l.Next()
	yyrule = 53
	l.Mark()
	switch {
	default:
		goto yyrule53
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate114:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'a':
		goto yystate115
	case c == 'o':
		goto yystate117
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'n' || c >= 'p' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate115:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'p':
		goto yystate116
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'o' || c >= 'q' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate116:
	c = l.Next()
	yyrule = 59
	l.Mark()
	switch {
	default:
		goto yyrule59
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate117:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'n':
		goto yystate118
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate118:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'e':
		goto yystate119
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate119:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'y':
		goto yystate120
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'x' || c == 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate120:
	c = l.Next()
	yyrule = 55
	l.Mark()
	switch {
	default:
		goto yyrule55
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate121:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'i':
		goto yystate122
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate122:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'l':
		goto yystate123
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'k' || c >= 'm' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate123:
	c = l.Next()
	yyrule = 50
	l.Mark()
	switch {
	default:
		goto yyrule50
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate124:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'e':
		goto yystate125
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate125:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 't':
		goto yystate126
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate126:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'u':
		goto yystate127
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 't' || c >= 'v' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate127:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'r':
		goto yystate128
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate128:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'n':
		goto yystate129
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate129:
	c = l.Next()
	yyrule = 51
	l.Mark()
	switch {
	default:
		goto yyrule51
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate130:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 't':
		goto yystate131
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate131:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'r':
		goto yystate132
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate132:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'i':
		goto yystate133
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate133:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'n':
		goto yystate134
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate134:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'g':
		goto yystate135
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'f' || c >= 'h' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate135:
	c = l.Next()
	yyrule = 56
	l.Mark()
	switch {
	default:
		goto yyrule56
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate136:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'r':
		goto yystate137
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate137:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'u':
		goto yystate138
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 't' || c >= 'v' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate138:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'e':
		goto yystate139
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate139:
	c = l.Next()
	yyrule = 40
	l.Mark()
	switch {
	default:
		goto yyrule40
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate140:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'a':
		goto yystate141
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate141:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'r':
		goto yystate142
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate142:
	c = l.Next()
	yyrule = 39
	l.Mark()
	switch {
	default:
		goto yyrule39
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate143:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'a':
		goto yystate144
	case c == 'h':
		goto yystate150
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'g' || c >= 'i' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate144:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'r':
		goto yystate145
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate145:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'n':
		goto yystate146
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate146:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'i':
		goto yystate147
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate147:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'n':
		goto yystate148
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate148:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'g':
		goto yystate149
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'f' || c >= 'h' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate149:
	c = l.Next()
	yyrule = 48
	l.Mark()
	switch {
	default:
		goto yyrule48
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate150:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'i':
		goto yystate151
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate151:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'l':
		goto yystate152
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'k' || c >= 'm' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate152:
	c = l.Next()
	yyrule = 64
	l.Mark()
	switch {
	default:
		goto yyrule64
	case c == 'e':
		goto yystate153
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate153:
	c = l.Next()
	yyrule = 44
	l.Mark()
	switch {
	default:
		goto yyrule44
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate38
	}

yystate154:
	c = l.Next()
	yyrule = 30
	l.Mark()
	goto yyrule30

yystate155:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == '|':
		goto yystate156
	}

yystate156:
	c = l.Next()
	yyrule = 11
	l.Mark()
	goto yyrule11

yystate157:
	c = l.Next()
	yyrule = 31
	l.Mark()
	goto yyrule31

yyrule1: // [ \t\r\n ]+
	{
		// ignore all whitespace
		goto yystate0
	}
yyrule2: // \+=
	{
		return l.char(ADD_ASSIGN)
	}
yyrule3: // -=
	{
		return l.char(SUB_ASSIGN)
	}
yyrule4: // \*=
	{
		return l.char(MUL_ASSIGN)
	}
yyrule5: // \/=
	{
		return l.char(DIV_ASSIGN)
	}
yyrule6: // %=
	{
		return l.char(MOD_ASSIGN)
	}
yyrule7: // =
	{
		return l.char(ASSIGN)
	}
yyrule8: // \+\+
	{
		return l.char(INC)
	}
yyrule9: // --
	{
		return l.char(DEC)
	}
yyrule10: // &&
	{
		return l.char(AND)
	}
yyrule11: // \|\|
	{
		return l.char(OR)
	}
yyrule12: // \+
	{
		return l.char(ADD)
	}
yyrule13: // -
	{
		return l.char(SUB)
	}
yyrule14: // \*
	{
		return l.char(MUL)
	}
yyrule15: // \/
	{
		return l.char(DIV)
	}
yyrule16: // %
	{
		return l.char(MOD)
	}
yyrule17: // ==
	{
		return l.char(EQ)
	}
yyrule18: // !=
	{
		return l.char(NOT_EQ)
	}
yyrule19: // !
	{
		return l.char(NOT)
	}
yyrule20: // \<=
	{
		return l.char(LTE)
	}
yyrule21: // >=
	{
		return l.char(GTE)
	}
yyrule22: // \<
	{
		return l.char(LT)
	}
yyrule23: // >
	{
		return l.char(GT)
	}
yyrule24: // \.\.\.
	{
		return l.char(ELLIPSIS)
	}
yyrule25: // \.
	{
		return l.char(DOT)
	}
yyrule26: // ,
	{
		return l.char(COMMA)
	}
yyrule27: // :
	{
		return l.char(COLON)
	}
yyrule28: // \(
	{
		return l.char(LPAREN)
	}
yyrule29: // \)
	{
		return l.char(RPAREN)
	}
yyrule30: // \{
	{
		return l.char(LBRACE)
	}
yyrule31: // \}
	{
		return l.char(RBRACE)
	}
yyrule32: // \[
	{
		return l.char(LBRAKET)
	}
yyrule33: // \]
	{
		return l.char(RBRAKET)
	}
yyrule34: // contract
	{
		return l.char(CONTRACT)
	}
yyrule35: // data
	{
		return l.char(DATA)
	}
yyrule36: // condition
	{
		return l.char(CONDITION)
	}
yyrule37: // action
	{
		return l.char(ACTION)
	}
yyrule38: // func
	{
		return l.char(FUNC)
	}
yyrule39: // var
	{
		return l.char(VAR)
	}
yyrule40: // true
	{
		return l.char(TRUE)
	}
yyrule41: // false
	{
		return l.char(FALSE)
	}
yyrule42: // if
	{
		return l.char(IF)
	}
yyrule43: // else
	{
		return l.char(ELSE)
	}
yyrule44: // while
	{
		return l.char(WHILE)
	}
yyrule45: // break
	{
		return l.char(BREAK)
	}
yyrule46: // continue
	{
		return l.char(CONTINUE)
	}
yyrule47: // info
	{
		return l.char(INFO)
	}
yyrule48: // warning
	{
		return l.char(WARNING)
	}
yyrule49: // error
	{
		return l.char(ERROR)
	}
yyrule50: // nil
	{
		return l.char(NIL)
	}
yyrule51: // return
	{
		return l.char(RETURN)
	}
yyrule52: // bool
	{
		return l.char(T_BOOL)
	}
yyrule53: // int
	{
		return l.char(T_INT)
	}
yyrule54: // float
	{
		return l.char(T_FLOAT)
	}
yyrule55: // money
	{
		return l.char(T_MONEY)
	}
yyrule56: // string
	{
		return l.char(T_STRING)
	}
yyrule57: // bytes
	{
		return l.char(T_BYTES)
	}
yyrule58: // array
	{
		return l.char(T_ARRAY)
	}
yyrule59: // map
	{
		return l.char(T_MAP)
	}
yyrule60: // file
	{
		return l.char(T_FILE)
	}
yyrule61: // \${identifier}
	{
		{
			lval.s = string(l.TokenBytes(nil))
			return l.char(EXTEND_VAR)
		}
		goto yystate0
	}
yyrule62: // {int}
	{
		{
			lval.i, _ = strconv.Atoi(string(l.TokenBytes(nil)))
			return l.char(INT)
		}
		goto yystate0
	}
yyrule63: // {float}
	{
		{
			lval.f, _ = strconv.ParseFloat(string(l.TokenBytes(nil)), 64)
			return l.char(FLOAT)
		}
		goto yystate0
	}
yyrule64: // {identifier}
	{
		{
			lval.s = string(l.TokenBytes(nil))
			return l.char(IDENT)
		}
		goto yystate0
	}
yyrule65: // {string}
	{
		{
			lval.s = string(l.TokenBytes(nil))
			return l.char(STRING)
		}
		goto yystate0
	}
	panic("unreachable")

	goto yyabort // silence unused label error

yyabort: // no lexem recognized
	if c, ok := l.Abort(); ok {
		return l.char(c)
	}

	goto yyAction
}
