package vde

var tablesDataSQL = `
INSERT INTO "1_tables" ("id", "name", "permissions","columns", "conditions", "ecosystem") VALUES 
(next_id('1_tables'), 'contracts', 
	'{"insert": "ContractConditions(\"MainCondition\")", "update": "ContractConditions(\"MainCondition\")", 
	  "new_column": "ContractConditions(\"MainCondition\")"}',
	'{"name": "false",
	  "value": "ContractConditions(\"MainCondition\")",
	  "conditions": "ContractConditions(\"MainCondition\")"}', 'ContractAccess("EditTable")', '%[1]d'),
	(next_id('1_tables'), 'languages', 
	'{"insert": "ContractConditions(\"MainCondition\")", "update": "ContractConditions(\"MainCondition\")", 
	  "new_column": "ContractConditions(\"MainCondition\")"}',
	'{ "name": "ContractConditions(\"MainCondition\")",
	  "res": "ContractConditions(\"MainCondition\")",
	  "conditions": "ContractConditions(\"MainCondition\")"}', 'ContractAccess("EditTable")', '%[1]d'),
	(next_id('1_tables'), 'menu', 
	'{"insert": "ContractConditions(\"MainCondition\")", "update": "ContractConditions(\"MainCondition\")", 
	  "new_column": "ContractConditions(\"MainCondition\")"}',
	'{"name": "ContractConditions(\"MainCondition\")",
"value": "ContractConditions(\"MainCondition\")",
"conditions": "ContractConditions(\"MainCondition\")"
	}', 'ContractAccess("EditTable")', '%[1]d'),
	(next_id('1_tables'), 'pages', 
	'{"insert": "ContractConditions(\"MainCondition\")", "update": "ContractConditions(\"MainCondition\")", 
	  "new_column": "ContractConditions(\"MainCondition\")"}',
	'{"name": "ContractConditions(\"MainCondition\")",
"value": "ContractConditions(\"MainCondition\")",
"menu": "ContractConditions(\"MainCondition\")",
"conditions": "ContractConditions(\"MainCondition\")",
"validate_count": "ContractConditions(\"MainCondition\")",
"validate_mode": "ContractConditions(\"MainCondition\")",
"app_id": "ContractConditions(\"MainCondition\")"
	}', 'ContractAccess("EditTable")', '%[1]d'),
	(next_id('1_tables'), 'blocks', 
	'{"insert": "ContractConditions(\"MainCondition\")", "update": "ContractConditions(\"MainCondition\")", 
	  "new_column": "ContractConditions(\"MainCondition\")"}',
	'{"name": "ContractConditions(\"MainCondition\")",
"value": "ContractConditions(\"MainCondition\")",
"conditions": "ContractConditions(\"MainCondition\")"
	}', 'ContractAccess("EditTable")', '%[1]d'),
	(next_id('1_tables'), 'cron',
	  '{"insert": "ContractConditions(\"MainCondition\")", "update": "ContractConditions(\"MainCondition\")",
		"new_column": "ContractConditions(\"MainCondition\")"}',
	  '{"owner": "ContractConditions(\"MainCondition\")",
	  "cron": "ContractConditions(\"MainCondition\")",
	  "contract": "ContractConditions(\"MainCondition\")",
	  "counter": "ContractConditions(\"MainCondition\")",
	  "till": "ContractConditions(\"MainCondition\")",
		"conditions": "ContractConditions(\"MainCondition\")"
	  }', 'ContractConditions("MainCondition")', '%[1]d'),
	(next_id('1_tables'), 'binaries',
	  '{"insert": "ContractConditions(\"MainCondition\")", "update": "ContractConditions(\"MainCondition\")",
		  "new_column": "ContractConditions(\"MainCondition\")"}',
	  '{"app_id": "ContractConditions(\"MainCondition\")",
		  "member_id": "ContractConditions(\"MainCondition\")",
		  "name": "ContractConditions(\"MainCondition\")",
		  "data": "ContractConditions(\"MainCondition\")",
		  "hash": "ContractConditions(\"MainCondition\")",
		  "mime_type": "ContractConditions(\"MainCondition\")"}',
			'ContractConditions("MainCondition")', '%[1]d'),
	(next_id('1_tables'), 'keys',
	  '{"insert": "ContractConditions(\"MainCondition\")", "update": "ContractConditions(\"MainCondition\")",
			"new_column": "ContractConditions(\"MainCondition\")"}',
		'{"pub": "ContractConditions(\"MainCondition\")",
			"multi": "ContractConditions(\"MainCondition\")",
			"deleted": "ContractConditions(\"MainCondition\")",
			"blocked": "ContractConditions(\"MainCondition\")"}',
		'ContractConditions("MainCondition")', '%[1]d');	 
`
