// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

const _TokenType_name = "EOFIllegalNewLineIdentIntFloatStringAssignPlusMinusAsteriskSlashPercentBangLtGtLtEqGtEqEqNotEqAndOrDotCommaLParenRParenLBraceRBraceLBraketRBraketColonTailContractDataConditionActionFuncVarExtendVarTrueFalseIfElseWhileBreakContinueInfoWarningErrorNilReturnTypeBoolTypeIntTypeFloatTypeMoneyTypeStringTypeBytesTypeArrayTypeMapTypeFile"

var _TokenType_index = [...]uint16{0, 3, 10, 17, 22, 25, 30, 36, 42, 46, 51, 59, 64, 71, 75, 77, 79, 83, 87, 89, 94, 97, 99, 102, 107, 113, 119, 125, 131, 138, 145, 150, 154, 162, 166, 175, 181, 185, 188, 197, 201, 206, 208, 212, 217, 222, 230, 234, 241, 246, 249, 255, 263, 270, 279, 288, 298, 307, 316, 323, 331}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
