/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.golang.app;

public final class R {
    public static final class array {
        public static final int xwalk_resources_list=0x7f0a0000;
    }
    public static final class attr {
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int metaButtonBarButtonStyle=0x7f010001;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int metaButtonBarStyle=0x7f010000;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int select_dialog_multichoice=0x7f010002;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int select_dialog_singlechoice=0x7f010003;
    }
    public static final class bool {
        public static final int use_activity=0x7f050000;
        public static final int use_provider=0x7f050001;
    }
    public static final class color {
        public static final int black_overlay=0x7f060000;
        public static final int color_picker_background_color=0x7f060002;
        public static final int color_picker_border_color=0x7f060001;
        public static final int dropdown_dark_divider_color=0x7f060004;
        public static final int dropdown_divider_color=0x7f060003;
        public static final int keyboard_accessory_suggestion_background_color=0x7f060005;
    }
    public static final class dimen {
        public static final int activity_horizontal_margin=0x7f070001;
        public static final int activity_vertical_margin=0x7f070000;
        public static final int color_button_height=0x7f070004;
        /** 
         14.5 = Seekbar thumb width - border width, but it depends on the width
         of the seek bar icon.
    
         */
        public static final int color_picker_gradient_margin=0x7f070003;
        /** 
         Fallback values if the corresponding com.android.internal.R dimensions
         cannot be retrieved by name.
         Note: Constants taken directly from Android's core/res/values/config.xml.
    
         */
        public static final int config_min_scaling_span=0x7f070007;
        public static final int config_min_scaling_touch_major=0x7f070008;
        public static final int dropdown_item_divider_height=0x7f070006;
        public static final int dropdown_item_height=0x7f070005;
        /**  Link Preview dimensions 
         */
        public static final int link_preview_overlay_radius=0x7f070002;
    }
    public static final class drawable {
        public static final int dropdown_popup_background=0x7f020000;
        public static final int dropdown_popup_background_down=0x7f020001;
        public static final int dropdown_popup_background_up=0x7f020002;
        public static final int ic_chooser=0x7f020003;
        public static final int ic_menu_share_holo_light=0x7f020004;
        public static final int ic_search=0x7f020005;
        public static final int ic_warning=0x7f020006;
        public static final int icon=0x7f020007;
    }
    public static final class id {
        public static final int activity_main=0x7f090002;
        public static final int dropdown_popup_window=0x7f090000;
        public static final int webView1=0x7f090001;
    }
    public static final class layout {
        public static final int webview=0x7f030000;
        public static final int xwalk=0x7f030001;
    }
    public static final class string {
        public static final int accessibility_date_picker_month=0x7f04001d;
        public static final int accessibility_date_picker_week=0x7f040021;
        public static final int accessibility_date_picker_year=0x7f04001e;
        public static final int accessibility_datetime_picker_date=0x7f04002f;
        public static final int accessibility_datetime_picker_time=0x7f040030;
        public static final int accessibility_time_picker_ampm=0x7f04002a;
        public static final int accessibility_time_picker_hour=0x7f040026;
        public static final int accessibility_time_picker_milli=0x7f040029;
        public static final int accessibility_time_picker_minute=0x7f040027;
        public static final int accessibility_time_picker_second=0x7f040028;
        public static final int action_settings=0x7f040045;
        public static final int actionbar_share=0x7f040000;
        public static final int actionbar_web_search=0x7f040001;
        public static final int app_name=0x7f040043;
        public static final int autofill_popup_content_description=0x7f040034;
        public static final int choose_file=0x7f04004a;
        public static final int choose_upload=0x7f040047;
        public static final int color_picker_button_black=0x7f04001a;
        public static final int color_picker_button_blue=0x7f040016;
        public static final int color_picker_button_cancel=0x7f040012;
        public static final int color_picker_button_cyan=0x7f040015;
        public static final int color_picker_button_green=0x7f040017;
        public static final int color_picker_button_magenta=0x7f040018;
        public static final int color_picker_button_more=0x7f04000d;
        public static final int color_picker_button_red=0x7f040014;
        public static final int color_picker_button_set=0x7f040011;
        public static final int color_picker_button_white=0x7f04001b;
        public static final int color_picker_button_yellow=0x7f040019;
        public static final int color_picker_dialog_title=0x7f040013;
        public static final int color_picker_hue=0x7f04000e;
        public static final int color_picker_saturation=0x7f04000f;
        public static final int color_picker_value=0x7f040010;
        public static final int copy_to_clipboard_failure_message=0x7f04001c;
        public static final int crosswalk_install_title=0x7f04004d;
        public static final int date_picker_dialog_clear=0x7f040033;
        public static final int date_picker_dialog_other_button_label=0x7f040031;
        public static final int date_picker_dialog_set=0x7f04001f;
        public static final int date_picker_dialog_title=0x7f040032;
        public static final int date_time_picker_dialog_title=0x7f04002e;
        public static final int decompression_progress_message=0x7f04004e;
        public static final int download_already_exists_toast=0x7f04003b;
        public static final int download_failed_device_not_found=0x7f040051;
        public static final int download_failed_insufficient_space=0x7f040052;
        public static final int download_failed_message=0x7f040050;
        public static final int download_failed_time_out=0x7f040053;
        public static final int download_failed_toast=0x7f04003c;
        public static final int download_finished_toast=0x7f04003d;
        public static final int download_no_permission_toast=0x7f04003a;
        public static final int download_progress_message=0x7f04004f;
        public static final int download_start_toast=0x7f040039;
        public static final int empty_directory=0x7f040048;
        public static final int error_selecting_file=0x7f04004b;
        public static final int hello_world=0x7f040044;
        public static final int http_auth_log_in=0x7f040042;
        public static final int http_auth_password=0x7f040041;
        public static final int http_auth_title=0x7f04003f;
        public static final int http_auth_user_name=0x7f040040;
        public static final int internal_storage=0x7f04004c;
        public static final int js_alert_title=0x7f040036;
        public static final int js_confirm_title=0x7f040037;
        public static final int js_prompt_title=0x7f040038;
        public static final int low_memory_error=0x7f04000b;
        public static final int market_open_failed_message=0x7f040054;
        public static final int media_player_error_button=0x7f040005;
        public static final int media_player_error_text_invalid_progressive_playback=0x7f040003;
        public static final int media_player_error_text_unknown=0x7f040004;
        public static final int media_player_error_title=0x7f040002;
        public static final int media_player_loading_video=0x7f040006;
        public static final int month_picker_dialog_title=0x7f040020;
        public static final int opening_file_error=0x7f04000c;
        public static final int password_generation_popup_content_description=0x7f040035;
        public static final int profiler_error_toast=0x7f04000a;
        public static final int profiler_no_storage_toast=0x7f040009;
        public static final int profiler_started_toast=0x7f040007;
        public static final int profiler_stopped_toast=0x7f040008;
        public static final int ssl_alert_title=0x7f04003e;
        public static final int startup_architecture_mismatch_message=0x7f040058;
        public static final int startup_architecture_mismatch_title=0x7f040057;
        public static final int startup_newer_version_message=0x7f04005e;
        public static final int startup_newer_version_title=0x7f04005d;
        public static final int startup_not_found_message=0x7f040056;
        public static final int startup_not_found_title=0x7f040055;
        public static final int startup_older_version_message=0x7f04005c;
        public static final int startup_older_version_title=0x7f04005b;
        public static final int startup_signature_check_error_message=0x7f04005a;
        public static final int startup_signature_check_error_title=0x7f040059;
        public static final int storage_removed=0x7f040049;
        public static final int time_picker_dialog_am=0x7f040023;
        public static final int time_picker_dialog_hour_minute_separator=0x7f04002b;
        public static final int time_picker_dialog_minute_second_separator=0x7f04002c;
        public static final int time_picker_dialog_pm=0x7f040024;
        public static final int time_picker_dialog_second_subsecond_separator=0x7f04002d;
        public static final int time_picker_dialog_title=0x7f040025;
        public static final int uploads_disabled=0x7f040046;
        public static final int week_picker_dialog_title=0x7f040022;
        public static final int xwalk_cancel=0x7f04005f;
        public static final int xwalk_close=0x7f040061;
        public static final int xwalk_continue=0x7f040060;
        public static final int xwalk_retry=0x7f040062;
    }
    public static final class style {
        public static final int DropdownPopupWindow=0x7f080003;
        public static final int SelectActionMenuShare=0x7f080001;
        public static final int SelectActionMenuWebSearch=0x7f080002;
        public static final int SelectPopupDialog=0x7f080000;
    }
    public static final class styleable {
        /**  Declare custom theme attributes that allow changing which styles are
         used for button bars depending on the API level.
         ?android:attr/buttonBarStyle is new as of API 11 so this is
         necessary to support previous API levels. 
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #ButtonBarContainerTheme_metaButtonBarButtonStyle org.golang.app:metaButtonBarButtonStyle}</code></td><td></td></tr>
           <tr><td><code>{@link #ButtonBarContainerTheme_metaButtonBarStyle org.golang.app:metaButtonBarStyle}</code></td><td></td></tr>
           </table>
           @see #ButtonBarContainerTheme_metaButtonBarButtonStyle
           @see #ButtonBarContainerTheme_metaButtonBarStyle
         */
        public static final int[] ButtonBarContainerTheme = {
            0x7f010000, 0x7f010001
        };
        /**
          <p>This symbol is the offset where the {@link org.golang.app.R.attr#metaButtonBarButtonStyle}
          attribute's value can be found in the {@link #ButtonBarContainerTheme} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name org.golang.app:metaButtonBarButtonStyle
        */
        public static final int ButtonBarContainerTheme_metaButtonBarButtonStyle = 1;
        /**
          <p>This symbol is the offset where the {@link org.golang.app.R.attr#metaButtonBarStyle}
          attribute's value can be found in the {@link #ButtonBarContainerTheme} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name org.golang.app:metaButtonBarStyle
        */
        public static final int ButtonBarContainerTheme_metaButtonBarStyle = 0;
    };
}
